// <auto-generated />
namespace PERA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BadgeScan_BadgeID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BadgeScan_BadgeID));
        
        string IMigrationMetadata.Id
        {
            get { return "201504120328449_BadgeScan_BadgeID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
