// <auto-generated />
namespace PERA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PRTM_IAPRid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PRTM_IAPRid));
        
        string IMigrationMetadata.Id
        {
            get { return "201503301543048_PRTM_IAPRid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
